"use client";
import { MovieListUI } from "../components/movies/MovieListUI";

// let movies: MovieProps[] = [
//   {
//     _id: "66d48e1b1ee13f66b4698127",
//     title: "Inception",
//     release_date: "2010-07-16T00:00:00.000Z",
//     genre: ["Action", "Sci-Fi", "Thriller"],
//     director: "Christopher Nolan",
//     cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
//     plot_summary:
//       "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
//     duration: 148,
//     language: "English",
//     rating: 8.8,
//     production_company: "Warner Bros.",
//     screenplay_writer: "Christopher Nolan",
//     music_composer: "Hans Zimmer",
//     awards: ["Oscar for Best Cinematography", "Oscar for Best Sound Mixing"],
//     age_rating: "PG-13",
//     __v: 0,
//   },
//   {
//     _id: "66d48e2d1ee13f66b4698129",
//     title: "The Dark Knight",
//     release_date: "2008-07-18T00:00:00.000Z",
//     genre: ["Action", "Crime", "Drama"],
//     director: "Christopher Nolan",
//     cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
//     plot_summary:
//       "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
//     duration: 152,
//     language: "English",
//     rating: 9,
//     production_company: "Warner Bros.",
//     screenplay_writer: "Jonathan Nolan, Christopher Nolan",
//     music_composer: "Hans Zimmer, James Newton Howard",
//     awards: ["Oscar for Best Supporting Actor", "Oscar for Best Sound Editing"],
//     age_rating: "PG-13",
//     __v: 0,
//   },
//   {
//     _id: "66d48e371ee13f66b469812b",
//     title: "Interstellar",
//     release_date: "2014-11-07T00:00:00.000Z",
//     genre: ["Adventure", "Drama", "Sci-Fi"],
//     director: "Christopher Nolan",
//     cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
//     plot_summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
//     duration: 169,
//     language: "English",
//     rating: 8.6,
//     production_company: "Paramount Pictures",
//     screenplay_writer: "Jonathan Nolan, Christopher Nolan",
//     music_composer: "Hans Zimmer",
//     awards: ["Oscar for Best Visual Effects"],
//     age_rating: "PG-13",
//     __v: 0,
//   },
//   {
//     _id: "66d48e421ee13f66b469812d",
//     title: "The Matrix",
//     release_date: "1999-03-31T00:00:00.000Z",
//     genre: ["Action", "Sci-Fi"],
//     director: "Lana Wachowski, Lilly Wachowski",
//     cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
//     plot_summary:
//       "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
//     duration: 136,
//     language: "English",
//     rating: 8.7,
//     production_company: "Warner Bros.",
//     screenplay_writer: "Lana Wachowski, Lilly Wachowski",
//     music_composer: "Don Davis",
//     awards: ["Oscar for Best Film Editing", "Oscar for Best Sound"],
//     age_rating: "R",
//     __v: 0,
//   },
//   {
//     _id: "66d48e4c1ee13f66b469812f",
//     title: "Pulp Fiction",
//     release_date: "1994-10-14T00:00:00.000Z",
//     genre: ["Crime", "Drama"],
//     director: "Quentin Tarantino",
//     cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
//     plot_summary:
//       "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.",
//     duration: 154,
//     language: "English",
//     rating: 8.9,
//     production_company: "Miramax",
//     screenplay_writer: "Quentin Tarantino, Roger Avary",
//     music_composer: "Various Artists",
//     awards: ["Oscar for Best Original Screenplay"],
//     age_rating: "R",
//     __v: 0,
//   },
//   {
//     _id: "66d48e551ee13f66b4698131",
//     title: "The Shawshank Redemption",
//     release_date: "1994-09-23T00:00:00.000Z",
//     genre: ["Drama"],
//     director: "Frank Darabont",
//     cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
//     plot_summary:
//       "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
//     duration: 142,
//     language: "English",
//     rating: 9.3,
//     production_company: "Castle Rock Entertainment",
//     screenplay_writer: "Frank Darabont",
//     music_composer: "Thomas Newman",
//     awards: ["Nominated for 7 Oscars"],
//     age_rating: "R",
//     __v: 0,
//   },
//   {
//     _id: "66d48e5e1ee13f66b4698133",
//     title: "Forrest Gump",
//     release_date: "1994-07-06T00:00:00.000Z",
//     genre: ["Drama", "Romance"],
//     director: "Robert Zemeckis",
//     cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
//     plot_summary:
//       "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
//     duration: 142,
//     language: "English",
//     rating: 8.8,
//     production_company: "Paramount Pictures",
//     screenplay_writer: "Eric Roth",
//     music_composer: "Alan Silvestri",
//     awards: ["Oscar for Best Picture", "Oscar for Best Actor"],
//     age_rating: "PG-13",
//     __v: 0,
//   },
//   {
//     _id: "66d48e671ee13f66b4698135",
//     title: "The Godfather",
//     release_date: "1972-03-24T00:00:00.000Z",
//     genre: ["Crime", "Drama"],
//     director: "Francis Ford Coppola",
//     cast: ["Marlon Brando", "Al Pacino", "James Caan"],
//     plot_summary:
//       "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
//     duration: 175,
//     language: "English",
//     rating: 9.2,
//     production_company: "Paramount Pictures",
//     screenplay_writer: "Mario Puzo, Francis Ford Coppola",
//     music_composer: "Nino Rota",
//     awards: ["Oscar for Best Picture", "Oscar for Best Actor"],
//     age_rating: "R",
//     __v: 0,
//   },
//   {
//     _id: "66d48e701ee13f66b4698137",
//     title: "Fight Club",
//     release_date: "1999-10-15T00:00:00.000Z",
//     genre: ["Drama"],
//     director: "David Fincher",
//     cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
//     plot_summary:
//       "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
//     duration: 139,
//     language: "English",
//     rating: 8.8,
//     production_company: "20th Century Fox",
//     screenplay_writer: "Jim Uhls",
//     music_composer: "The Dust Brothers",
//     awards: ["Nominated for 1 Oscar"],
//     age_rating: "R",
//     __v: 0,
//   },
//   {
//     _id: "66d48e791ee13f66b4698139",
//     title: "The Lord of the Rings: The Fellowship of the Ring",
//     release_date: "2001-12-19T00:00:00.000Z",
//     genre: ["Adventure", "Drama", "Fantasy"],
//     director: "Peter Jackson",
//     cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
//     plot_summary:
//       "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
//     duration: 178,
//     language: "English",
//     rating: 8.8,
//     production_company: "New Line Cinema",
//     screenplay_writer: "Fran Walsh, Philippa Boyens, Peter Jackson",
//     music_composer: "Howard Shore",
//     awards: ["Oscar for Best Cinematography", "Oscar for Best Makeup"],
//     age_rating: "PG-13",
//     __v: 0,
//   },
// ];
export default function MovieList() {
  return <MovieListUI />;
}
